In [ ]:

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


In [ ]:
with open("/content/2024_state_of_the_union.txt",'r',encoding = 'utf-8') as myfile:
  mytext = myfile.read()

In [ ]:
mytext

'March 07, 2024\nRemarks of President Joe Biden — State of the Union Address As Prepared for Delivery\nHome\nBriefing Room\nSpeeches and Remarks\nThe United States Capitol\n\n###\n\nGood evening. \n\nMr. Speaker. Madam Vice President. Members of Congress. My Fellow Americans. \n\nIn January 1941, President Franklin Roosevelt came to this chamber to speak to the nation. \n\nHe said, “I address you at a moment unprecedented in the history of the Union.” \n\nHitler was on the march. War was raging in Europe. \n\nPresident Roosevelt’s purpose was to wake up the Congress and alert the American people that this was no ordinary moment.   \n\nFreedom and democracy were under assault in the world. \n\nTonight I come to the same chamber to address the nation. \n\nNow it is we who face an unprecedented moment in the history of the Union. \n\nAnd yes, my purpose tonight is to both wake up this Congress, and alert the American people that this is no ordinary moment either. \n\nNot since President L

In [ ]:
#text ---> tokens--->numbers --->sequences --->LSTM

#tokenizer---split the text into words
#remov ethe punctuation - bydefault
#convert words into lower



In [ ]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index)+1 #index 0 is reserved for padding/unknown words

total words = 5000
vocab size= 5001

In [ ]:
mytokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'in': 6,
 'i': 7,
 'for': 8,
 'that': 9,
 'we': 10,
 'is': 11,
 'it': 12,
 'my': 13,
 'our': 14,
 'more': 15,
 'america': 16,
 'on': 17,
 'are': 18,
 'you': 19,
 'american': 20,
 'not': 21,
 'this': 22,
 'will': 23,
 'but': 24,
 'with': 25,
 'all': 26,
 'at': 27,
 'have': 28,
 'now': 29,
 'people': 30,
 'so': 31,
 'president': 32,
 'as': 33,
 'no': 34,
 'by': 35,
 'americans': 36,
 'down': 37,
 'future': 38,
 'was': 39,
 'they': 40,
 'can': 41,
 'want': 42,
 'from': 43,
 'home': 44,
 'up': 45,
 'it’s': 46,
 'than': 47,
 'their': 48,
 'has': 49,
 'here': 50,
 'be': 51,
 'i’ve': 52,
 'tonight': 53,
 'who': 54,
 'when': 55,
 'because': 56,
 'i’m': 57,
 'history': 58,
 'or': 59,
 'pay': 60,
 'year': 61,
 'do': 62,
 'make': 63,
 'tax': 64,
 'world': 65,
 'an': 66,
 'been': 67,
 'years': 68,
 'get': 69,
 'that’s': 70,
 '000': 71,
 'us': 72,
 'fair': 73,
 'families': 74,
 'act': 75,
 'care': 76,
 'predecessor': 77,
 'me': 78,
 'like': 79,
 '

In [ ]:
my_input_sequences = []
for line in mytext.split('\n'):
  token_list =mytokenizer.texts_to_sequences([line])[0]
  #print(token_list)
  for i in range(1,len(token_list)):
    my_n_gram_sequence = token_list[:i +1]
    my_input_sequences.append(my_n_gram_sequence)



why we are giving zero?
texts_to_sequences returns a list of lists
we are taking only [0] to accessthe sequence

In [ ]:
my_input_sequences

[[270, 744],
 [270, 744, 482],
 [483, 4],
 [483, 4, 32],
 [483, 4, 32, 745],
 [483, 4, 32, 745, 746],
 [483, 4, 32, 745, 746, 484],
 [483, 4, 32, 745, 746, 484, 151],
 [483, 4, 32, 745, 746, 484, 151, 4],
 [483, 4, 32, 745, 746, 484, 151, 4, 1],
 [483, 4, 32, 745, 746, 484, 151, 4, 1, 181],
 [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343],
 [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33],
 [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33, 747],
 [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33, 747, 8],
 [483, 4, 32, 745, 746, 484, 151, 4, 1, 181, 343, 33, 747, 8, 748],
 [749, 485],
 [750, 2],
 [750, 2, 483],
 [1, 182],
 [1, 182, 132],
 [1, 182, 132, 486],
 [223, 751],
 [487, 752],
 [487, 752, 753],
 [487, 752, 753, 224],
 [487, 752, 753, 224, 32],
 [487, 752, 753, 224, 32, 488],
 [487, 752, 753, 224, 32, 488, 4],
 [487, 752, 753, 224, 32, 488, 4, 111],
 [487, 752, 753, 224, 32, 488, 4, 111, 13],
 [487, 752, 753, 224, 32, 488, 4, 111, 13, 489],
 [487, 752, 753, 224, 32, 488

In [ ]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences,maxlen =max_sequence_len,padding = 'pre'))

In [ ]:
input_sequences[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       270, 744, 482], dtype=int32)

In [ ]:
X = input_sequences[:,:-1]
y =  input_sequences [:,-1]

In [ ]:
X[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       270, 744], dtype=int32)

In [ ]:
y

array([ 744,  482,    4, ...,  150,   14, 1623], dtype=int32)

In [ ]:
y = np.array(tf.keras.utils.to_categorical(y,num_classes = total_words))

In [ ]:
y[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
#build the model

model = Sequential()
model.add(Embedding(total_words, 100,input_length = max_sequence_len -1))
model.add(LSTM(150))
model.add(Dense(total_words,activation = "softmax")) #output layers
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.compile(loss = "categorical_crossentropy",optimizer ='adam',metrics =['accuracy'] )
model.fit(X,y,epochs = 100,verbose = 1)

Epoch 1/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.0403 - loss: 6.9065
Epoch 2/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.0459 - loss: 6.3164
Epoch 3/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.0506 - loss: 6.1347
Epoch 4/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.0644 - loss: 5.9803
Epoch 5/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.0735 - loss: 5.7874
Epoch 6/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.0840 - loss: 5.5874
Epoch 7/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.0956 - loss: 5.3951
Epoch 8/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1092 - loss: 5.1791
Epoch 9/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1151 - loss: 5.0497
Epoch 10/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1305 - loss: 4.8358
Epoch 11/100
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1528 - loss: 4.6557
Epoch 12/100
190/190 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
input_text = "We attempted to reach you on your"
predict_next_words= 20

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[10, 3, 19, 17, 140]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[10, 3, 19, 17, 140, 33]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[10, 3, 19, 17, 140, 33, 140]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[10, 3, 19, 17, 140, 33, 140, 44]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26, 36]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26, 36, 7]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26, 36, 7, 23]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26, 36, 7, 23, 21]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26, 36, 7, 23, 21, 515]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[10, 3, 19, 17, 140, 33, 140, 44, 3, 26, 36, 7, 23, 21, 515, 37]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[10, 3, 19, 17, 140, 33, 140,